receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  clickhouse:
    endpoint: "${CLICKHOUSE_ENDPOINT}"
    database: "${CLICKHOUSE_DATABASE}"
    username: "${CLICKHOUSE_USERNAME}"
    password: "${CLICKHOUSE_PASSWORD}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [clickhouse]
