receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  clickhouse:
    endpoint: "<ClickHouse_Endpoint>"
    database: "<Database_Name>"
    username: "<Username>"
    password: "<Password>"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [clickhouse]
